#!/bin/bash

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"

echo "Fixing rc scripts permissions:">> "${osxvolume}/Clover_Install_Log.txt"

# Fix permissions
chmod 755        "${osxvolume}/etc/rc.local"
chown root:wheel "${osxvolume}/etc/rc.local"
chmod 755        "${osxvolume}/etc/rc.shutdown.local"
chown root:wheel "${osxvolume}/etc/rc.shutdown.local"

cp -pf "${osxvolume}/etc/rc.local" "/etc/rc.local"
cp -pf "${osxvolume}/etc/rc.shutdown.local" "/etc/rc.shutdown.local"

ls -lad "${osxvolume}/etc/rc.local" >> "${osxvolume}/Clover_Install_Log.txt"
ls -lad "${osxvolume}/etc/rc.shutdown.local" >> "${osxvolume}/Clover_Install_Log.txt"
ls -lad "/etc/rc.local" >> "${osxvolume}/Clover_Install_Log.txt"
ls -lad "/etc/rc.shutdown.local" >> "${osxvolume}/Clover_Install_Log.txt"
echo "======================================================" >> "${osxvolume}/Clover_Install_Log.txt"
