#!/bin/bash

echo "==============================================="
echo "Post-Install RC Scripts"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"

echo "Copying RC scripts from ${osxvolume} to /" >> "${osxvolume}/Clover_Install_Log.txt"
cp -pf  "${osxvolume}/etc/rc.clover.lib" "/etc/"
cp -pf  "${osxvolume}/etc/rc.local" "/etc/rc.local"
cp -prf "${osxvolume}/etc/rc.boot.d" "/etc/"
cp -pf  "${osxvolume}/etc/rc.shutdown.local" "/etc/rc.shutdown.local"
cp -prf "${osxvolume}/etc/rc.shutdown.d" "/etc/"

if [[ -x "${osxvolume}/etc/custom.rc.local" ]]; then
	echo "Moving ${osxvolume}/etc/custom.rc.local to ${osxvolume}/etc/rc.boot.d/50.custom.local" \
	 >> "${osxvolume}/Clover_Install_Log.txt"
	cp -pf "${osxvolume}/etc/custom.rc.local" "${osxvolume}/etc/rc.boot.d/50.custom.local"
fi
if [[ -x "${osxvolume}/etc/custom.rc.shutdown.local" ]]; then
	echo "Moving ${osxvolume}/etc/custom.rc.shutdown.local to ${osxvolume}/etc/rc.shutdown.d/50.custom.local" \
	 >> "${osxvolume}/Clover_Install_Log.txt"
	cp -pf "${osxvolume}/etc/custom.rc.shutdown.local" "${osxvolume}/etc/rc.shutdown.d/50.custom.local"
fi

if [[ -x "/etc/custom.rc.local" ]]; then
	echo "Moving /etc/custom.rc.local to /etc/rc.boot.d/50.custom.local" \
	 >> "${osxvolume}/Clover_Install_Log.txt"
	cp -pf "/etc/custom.rc.local" "/etc/rc.boot.d/50.custom.local"
fi
if [[ -x "/etc/custom.rc.shutdown.local" ]]; then
	echo "Moving /etc/custom.rc.shutdown.local to /etc/rc.shutdown.d/50.custom.local" \
	 >> "${osxvolume}/Clover_Install_Log.txt"
	cp -pf "/etc/custom.rc.shutdown.local" "/etc/rc.shutdown.d/50.custom.local"
fi

echo "======================================================" >> "${osxvolume}/Clover_Install_Log.txt"
