#!/bin/bash

diskloader="boot0hfs"
partitionloaderhfs="boot1h2"
partitionloaderfat="boot1f32alt"

DEST_VOL="${3}"
EFI_ROOT_DIR="${DEST_VOL}/EFIROOTDIR"
CLOVER_INSTALLER_PLIST_NEW="${DEST_VOL}@CLOVER_INSTALLER_PLIST_NEW@"
install_log="${DEST_VOL}/Clover_Install_Log.txt"
installer_choice="@INSTALLER_CHOICE@"

bootvolume="$EFI_ROOT_DIR"
echo "Boot Volume is $bootvolume"
bootresources="${0%/*}"
echo "$bootresources"

if [ -z "${bootvolume}" ]; then
	echo
	echo "Cannot find the volume. Exiting."
	echo
	exit
fi

bootdev=$(LC_ALL=C diskutil info "$bootvolume" 2>/dev/null | \
 sed -n 's/.*Device Node: *//p')
bootrdev=${bootdev/disk/rdisk}

if [ "${bootdev}" = "${bootdev#*disk*s}" ]; then
	echo
	echo "ERROR Volume does not use slices."
	echo
	exit
fi

bootdisk=${bootdev%s*}
bootrdisk=${bootdisk/disk/rdisk}
bootslice=${bootdev#*disk*s}

echo "==============================================="
echo "Installer Variables:"
echo "********************"
echo "bootvolume: Volume is ${bootvolume}"
echo "bootdev: Volume device is ${bootdev}"
echo "bootrdev: Volume raw device is ${bootrdev}"
echo "bootslice: Volume slice is ${bootslice}"
echo "bootdisk: Disk device is ${bootdisk}"
echo "bootrdisk: Disk raw device is ${bootrdisk}"
echo "diskloader: Disk loader is ${diskloader}"
echo "partitionloaderhfs: Partition loader is ${partitionloaderhfs}"
echo "partitionloaderfat: Partition loader is ${partitionloaderfat}"
echo "bootresources: Boot Resources is ${bootresources}"
echo "-----------------------------------------------"
echo ""
echo ""

if [ ! -e "/usr/local/bin/fdisk440" ]; then
	mkdir -p /usr/local/bin
	cp -f "${DEST_VOL}/usr/local/bin/fdisk440" /usr/local/bin/fdisk440
fi

echo "==============================================="
echo "Check the format of the selected partition"
echo "==============================================="

if [ "$( fstyp ${bootdev} | grep hfs )" ]; then
	echo "${bootdev} is currently formatted as HFS"
	efiformat="hfs"
fi
if [ "$( fstyp ${bootdev} | grep msdos )" ]; then
	echo "${bootdev} is currently formatted as msdos"
	efiformat="msdos"
fi 
echo "-----------------------------------------------"

echo "======================================================" >> "$install_log"
echo "Installing BootSectors/BootLoader" >> "$install_log"
echo "" >> "$install_log"
partitionactive=$( /usr/local/bin/fdisk440 -d ${bootrdisk} | grep -n "*" | awk -F: '{print $1}')
echo "Current Active Partition: ${partitionactive}" >> "$install_log"
echo "" >> "$install_log"

### Stage 0 ###

echo "Stage 0 - Written ${diskloader} to ${bootdisk}" >> "$install_log"
echo "/usr/local/bin/fdisk440 -u -f ${DEST_VOL}/usr/standalone/i386/${diskloader} -y ${bootdisk}" >> "$install_log"
echo " " >> "$install_log"

/usr/local/bin/fdisk440 -u -f "${DEST_VOL}/usr/standalone/i386/${diskloader}" -y ${bootdisk}

### Stage 1 ###

if [ ${efiformat} = "hfs" ]; then
	echo "Executing command: dd if=/usr/standalone/i386/${partitionloaderhfs} of=${bootrdev}"

	echo "Stage 1 - Written ${partitionloaderhfs} to ${bootrdev}" >> "$install_log"
	echo "File system is HFS." >> "$install_log"
	echo "dd if=${DEST_VOL}/usr/standalone/i386/${partitionloaderhfs} of=${bootrdev}" >> "$install_log"
	echo " " >> "$install_log"

	dd if="${DEST_VOL}/usr/standalone/i386/${partitionloaderhfs}" of=${bootrdev}

	echo "${efiformat}" > "${DEST_VOL}/formattype"
fi

if [ ${efiformat} = "msdos" ]; then
	echo "Prepare Stage 1 loader"

	rm -f /tmp/origbs
	rm -f /tmp/newbs

	# copy partition boot sector to origbs
	echo "Executing command: dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs"
	dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs

	# copy boot1f32 to newbs
	echo "Executing command: cp ${DEST_VOL}/usr/standalone/i386/${partitionloaderfat} /tmp/newbs"
	cp "${DEST_VOL}/usr/standalone/i386/${partitionloaderfat}" /tmp/newbs
	
	# "merge" origbs into newbs
	echo "Executing command: dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc"
	dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc
	
	echo "Write Stage 1 loader"
	
	# write newbs to the partition boot sector
	echo "Executing command: dd if=/tmp/newbs of=${bootrdev}"
	dd if=/tmp/newbs of=${bootrdev}

	echo "Stage 1 - Written ${partitionloaderfat} to ${bootrdev}" >> "$install_log"
	echo "File system is Fat32." >> "$install_log"
	echo "dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs" >> "$install_log"
	echo "cp ${DEST_VOL}/usr/standalone/i386/${partitionloaderfat} /tmp/newbs" >> "$install_log"
	echo "dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc" >> "$install_log"
	echo "dd if=/tmp/newbs of=${bootrdev}" >> "$install_log"
	echo " " >> "$install_log"

	echo "${efiformat}" > "${DEST_VOL}/formattype"
	
	echo "Setup Active Partition to be : ${bootslice}" >> "$install_log"
	"/usr/local/bin/fdisk440" -e ${bootrdisk} <<-MAKEACTIVE
	print
	flag ${bootslice}
	write
	y
	quit
	MAKEACTIVE

fi

partitionactive=$( /usr/local/bin/fdisk440 -d ${bootrdisk} | grep -n "*" | awk -F: '{print $1}')
echo "New Active Partition: ${partitionactive}" >> "$install_log"
echo "" >> "$install_log"

echo "${diskloader}" > "${DEST_VOL}/boot0type"

# Mark that the option was selected
/usr/libexec/plistbuddy -c "Add $installer_choice bool true" "$CLOVER_INSTALLER_PLIST_NEW" >/dev/null

exit
