#!/bin/bash

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

DEST_VOL="${3}"
EFI_ROOT_DIR="${DEST_VOL}/EFIROOTDIR"
CLOVER_INSTALLER_PLIST_NEW="${DEST_VOL}@CLOVER_INSTALLER_PLIST_NEW@"
CLOVER_INSTALLER_PLIST="${DEST_VOL}@CLOVER_INSTALLER_PLIST@"
bootervolumename="EFI"
bootvolume="/Volumes/${bootervolumename}"
install_log="${DEST_VOL}/Clover_Install_Log.txt"
config_plist_file="${EFI_ROOT_DIR}"/EFI/Clover/config.plist

file "${DEST_VOL}/bootold" > "${DEST_VOL}/bootoldtype"
boottypeversion=$( grep "boot" "${DEST_VOL}/bootoldtype" | awk '{ print $2 }' | tr -d '}' )
echo "${boottypeversion}" >> "${DEST_VOL}/bootoldtype"
#echo "The original boot type = ${boottypeversion}" >> "$install_log"
if [[ "${boottypeversion}" == "data" ]]; then
    cp -f "${DEST_VOL}/bootold" "${DEST_VOL}/boot1"
    echo "cp -f ${DEST_VOL}/bootold ${DEST_VOL}/boot1" >> "$install_log"
    chflags hidden "${DEST_VOL}/boot1"
fi
rm -f "${DEST_VOL}/bootold"
rm -f "${DEST_VOL}/bootoldtype"

# Change config.plist if needed
boottype=$( cat "${DEST_VOL}/boottype" )

case "${boottype}" in
	ia32) perl -i -p -e "s/arch=x86_64/arch=i386/g" "${config_plist_file}" ;;
	 x64) perl -i -p -e "s/arch=i386/arch=x86_64/g" "${config_plist_file}" ;;
esac


echo "" >> "${install_log}"
echo "======================================================" >> "${install_log}"
echo "=========== Clover EFI Installation Finish ===========" >> "${install_log}"
echo "======================================================" >> "${install_log}"

# ---------------------------------------------
# Cleanup
# ---------------------------------------------

if [[ -e "$install_log" && -d "${EFI_ROOT_DIR}/EFI" ]]; then
    mv -f "$install_log" "${EFI_ROOT_DIR}/EFI/Clover_Install_Log.txt"
fi

if [[ -f "$CLOVER_INSTALLER_PLIST_NEW" ]]; then
    mv -f "$CLOVER_INSTALLER_PLIST_NEW" "$CLOVER_INSTALLER_PLIST"
fi

rm -f "${DEST_VOL}/boot0type"
rm -f "${DEST_VOL}/boottype"
rm -f "${DEST_VOL}/formattype"

rm -f "$EFI_ROOT_DIR"
