#!/bin/bash

echo "==============================================="
echo "Boot32 Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"
boottype='@CLOVER_EFI_ARCH@'
cloverEFIFile='@CLOVER_BOOT_FILE@'
installer_plist="${osxvolume}/EFI/CloverInstaller.plist"
installer_choice="@INSTALLER_CHOICE@"

echo "$boottype" > "${osxvolume}/boottype"

if [[ -f "${osxvolume}/boot" ]]; then
    cp "${osxvolume}/boot" "${osxvolume}/bootold"
fi

if [[ -f "${osxvolume}/usr/standalone/i386/$boottype/$cloverEFIFile" ]]; then
    cp -v "${osxvolume}/usr/standalone/i386/$boottype/$cloverEFIFile" "${osxvolume}/boot"
    chflags hidden "${osxvolume}/boot"
    echo "Stage 2 - Written $cloverEFIFile ($boottype) to ${osxvolume}/boot" >> "${osxvolume}/Clover_Install_Log.txt"
fi

# Mark that the option was selected
/usr/libexec/plistbuddy -c "Add $installer_choice bool true" "$installer_plist" >/dev/null
