#!/bin/bash

# Workspace = edk2/Clover/CloverPackage

# Copy the Version.h to workspace.

cp -f ../rEFIt_UEFI/Version.h Version.h

version=v2
#version=$( grep "FIRMWARE_VERSION" Version.h | awk '{ print $3 }' | tr -d '\"' )
revision=$( grep "FIRMWARE_REVISION" Version.h | awk '{ print $3 }' | tr -d '\"' )

echo "${version}" > version
echo "${revision}" > revision

# 複製 Slice 原始 ia32/boot 到 ia32/boot
#cp -f ~/src/CloverPKG/Clover_Slice/CloverV2/boot-32/boot CloverV2/Bootloaders/ia32/boot
#cp -f ~/src/CloverPKG/Clover_Slice/CloverV2_rev${revision}/CloverV2/boot-32/boot CloverV2/Bootloaders/ia32/boot
# 複製 Slice 原始 ia32/boot 到 ia32/boot

# Copy doc to CloverV2/doc.

mkdir -p CloverV2/doc/
#cp -f ../BootHFS/Installation.txt  CloverV2/doc/Installation.txt
cp -f ../BootHFS/boot1f32-install.sh  CloverV2/doc/boot1f32-install.sh

# Prepare i386 for package installer.

sudo rm -rf sym
mkdir -p sym/i386
cp -Rf CloverV2/Bootloaders/* sym/i386/
cp -f CloverV2/BootSectors/* sym/i386/

# Prepare Resources for package installer.

rm -rf package/Resources
mkdir -p package/Resources
cp -Rf package/Resources-original/* package/Resources

cp -f package/Distribution-original package/Distribution
title="title>Clover ${version} r${revision} x32 x64 EFI bootloader"
perl -i -p -e "s/title>Clover_title/${title}/g" `find "package/Distribution" -type f`

##find "CloverV2" -name '.*' -depth -exec rm -rf {} \;
##find "package" -name '.*' -depth -exec rm -rf {} \;

########################################################################
# Change revision to be Clover:rEFIt_UEFI = 358:361 show as installer. #
########################################################################

# perl -i -p -e "s/%CLOVERREVISION%/358:361/g" `find "package/Resources" -type f`

echo " "
echo "Modify CloverV2/EFI or package/Resources if necessary."
echo " "
# read -p "Press Enter to start to build the installer."
echo " "

# Workspace = edk2/Clover/CloverPackage
# Start to build installer.

cp -f CloverV2/config.plist-FullSample/config.plist CloverV2/EFI/config-sample.plist

sudo make pkg

cd sym
zip Clover_${version}_r${revision}_EFI_x32_x64_pkg.zip Clover_${version}_r${revision}_EFI_x32_x64.pkg
zip Clover_${version}_r${revision}_EFI_x32_x64_pkg.zip Clover_${version}_r${revision}_EFI_x32_x64.pkg.md5
cd ..

# Workspace = edk2/Clover/CloverPackage/
# Remove temp files.

rm -rf package/Resources
rm -f package/Distribution

# Open the final folder.

ls -la sym
open sym

# Finish building installer.

exit 0
