//
//  ConfigSample1.h
//  cpp_tests_compare_settings
//
//  Created by Jief on 05/02/2021.
//  Copyright © 2021 JF Knudsen. All rights reserved.
//

#ifndef ConfigSample1_h
#define ConfigSample1_h

#ifndef _MSC_VER
const char* configSample1 = "\n\n\n\n\n\n\n\n\n\n\n"
"<?xml version=\"1.0\" encoding=\"UTF-8\"?> \n\
<!DOCTYPE plist PUBLIC \n\"-//Apple//DTD PLIST 1.0//EN\" \n\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"> \n\
<plist version=\"1.0\"> \n\
<dict> \n\
  <key>ACPI</key> \n\
  <dict> \n\
    <key>AutoMerge</key> \n\
    <true/> \n\
    <key>DSDT</key> \n\
    <dict> \n\
      <key>Debug</key> \n\
      <true/> \n\
      <key>DropOEM_DSM</key> \n\
      <dict> \n\
        <key>ATI</key> \n\
        <true/> \n\
        <key>Firewire</key> \n\
        <false/> \n\
        <key>HDA</key> \n\
        <false/> \n\
        <key>HDMI</key> \n\
        <false/> \n\
        <key>IDE</key> \n\
        <true/> \n\
        <key>IntelGFX</key> \n\
        <false/> \n\
        <key>LAN</key> \n\
        <false/> \n\
        <key>LPC</key> \n\
        <false/> \n\
        <key>NVidia</key> \n\
        <false/> \n\
        <key>SATA</key> \n\
        <false/> \n\
        <key>SmBUS</key> \n\
        <false/> \n\
        <key>USB</key> \n\
        <false/> \n\
        <key>WIFI</key> \n\
        <false/> \n\
      </dict> \n\
      <key>Fixes</key> \n\
      <dict> \n\
        <key>FixDarwin</key> \n\
        <true/> \n\
        <key>FixDisplay</key> \n\
        <true/> \n\
        <key>FixS3D</key> \n\
        <true/> \n\
      </dict> \n\
      <key>Name</key> \n\
      <string>aa</string> \n\
      <key>Patches</key> \n\
      <array> \n\
        <dict> \n\
          <key>Comment</key> \n\
          <string>ACPI1</string> \n\
          <key>Disabled</key> \n\
          <false/> \n\
          <key>Find</key> \n\
          <data> \n\
          AA== \n\
          </data> \n\
          <key>Replace</key> \n\
          <data> \n\
          AQ== \n\
          </data> \n\
        </dict> \n\
        <dict> \n\
          <key>Comment</key> \n\
          <string>ACPI2</string> \n\
          <key>Disabled</key> \n\
          <true/> \n\
          <key>Find</key> \n\
          <data> \n\
          Ag== \n\
          </data> \n\
          <key>Replace</key> \n\
          <data> \n\
          Aw== \n\
          </data> \n\
        </dict> \n\
        <dict> \n\
          <key>Comment</key> \n\
          <string>change EHC1 to EH01</string> \n\
          <key>Disabled</key> \n\
          <false/> \n\
          <key>Find</key> \n\
          <data> \n\
          RUhDMQ== \n\
          </data> \n\
          <key>Replace</key> \n\
          <data> \n\
          RUgwMQ== \n\
          </data> \n\
        </dict> \n\
      </array> \n\
      <key>ReuseFFFF</key> \n\
      <true/> \n\
      <key>Rtc8Allowed</key> \n\
      <true/> \n\
      <key>SlpSmiAtWake</key> \n\
      <true/> \n\
      <key>SuspendOverride</key> \n\
      <true/> \n\
    </dict> \n\
    <key>DisableAPSNAPLF</key> \n\
    <true/> \n\
    <key>DisableASPM</key> \n\
    <true/> \n\
    <key>DisabledAML</key> \n\
    <array> \n\
      <string>aa</string> \n\
      <string>bb</string> \n\
    </array> \n\
    <key>DropTables</key> \n\
    <array> \n\
      <dict> \n\
        <key>Signature</key> \n\
        <string>SSDT</string> \n\
        <key>TableId</key> \n\
        <string>CpuPm</string> \n\
      </dict> \n\
    </array> \n\
    <key>HaltEnabler</key> \n\
    <true/> \n\
    <key>PatchAPIC</key> \n\
    <true/> \n\
    <key>ResetAddress</key> \n\
    <string>01</string> \n\
    <key>ResetValue</key> \n\
    <string>02</string> \n\
    <key>SortedOrder</key> \n\
    <array> \n\
      <string>dd</string> \n\
      <string>cc</string> \n\
    </array> \n\
    <key>smartUPS</key> \n\
    <true/> \n\
  </dict> \n\
  <key>Boot</key> \n\
  <dict> \n\
    <key>Arguments</key> \n\
    <string>-v arch=i386 slide=0 dart=0 -xcpm darkwake=1 npci=0x2000 cpus=1 debug=0x100 aa</string> \n\
    <key>BlackList</key> \n\
    <array> \n\
      <string>hh</string> \n\
    </array> \n\
    <key>CustomLogo</key> \n\
    <string>Apple</string> \n\
    <key>Debug</key> \n\
    <true/> \n\
    <key>DefaultLoader</key> \n\
    <string>ii</string> \n\
    <key>DefaultVolume</key> \n\
    <string>LastBootedVolume</string> \n\
    <key>DisableCloverHotkeys</key> \n\
    <true/> \n\
    <key>HibernationFixup</key> \n\
    <true/> \n\
    <key>Legacy</key> \n\
    <string>LegacyBiosDefault</string> \n\
    <key>LegacyBiosDefaultEntry</key> \n\
    <integer>12</integer> \n\
    <key>NeverDoRecovery</key> \n\
    <true/> \n\
    <key>NeverHibernate</key> \n\
    <true/> \n\
    <key>NoEarlyProgress</key> \n\
    <true/> \n\
    <key>Policy</key> \n\
    <string>Allow</string> \n\
    <key>Secure</key> \n\
    <true/> \n\
    <key>SignatureFixup</key> \n\
    <true/> \n\
    <key>SkipHibernateTimeout</key> \n\
    <true/> \n\
    <key>StrictHibernate</key> \n\
    <true/> \n\
    <key>Timeout</key> \n\
    <integer>2</integer> \n\
    <key>WhiteList</key> \n\
    <array> \n\
      <string>ff</string> \n\
      <string>gg</string> \n\
    </array> \n\
    <key>XMPDetection</key> \n\
    <integer>1</integer> \n\
  </dict> \n\
  <key>BootGraphics</key> \n\
  <dict> \n\
    <key>DefaultBackgroundColor</key> \n\
    <string>0xF1F1F1</string> \n\
    <key>EFILoginHiDPI</key> \n\
    <integer>2</integer> \n\
    <key>UIScale</key> \n\
    <integer>4</integer> \n\
    <key>flagstate</key> \n\
    <integer>3</integer> \n\
  </dict> \n\
  <key>CPU</key> \n\
  <dict> \n\
    <key>BusSpeedkHz</key> \n\
    <integer>800</integer> \n\
    <key>C2</key> \n\
    <true/> \n\
    <key>C4</key> \n\
    <true/> \n\
    <key>C6</key> \n\
    <true/> \n\
    <key>FrequencyMHz</key> \n\
    <integer>2000</integer> \n\
    <key>HWPEnable</key> \n\
    <true/> \n\
    <key>HWPValue</key> \n\
    <string>0x7</string> \n\
    <key>Latency</key> \n\
    <string>0x3</string> \n\
    <key>QEMU</key> \n\
    <true/> \n\
    <key>QPI</key> \n\
    <integer>4</integer> \n\
    <key>TDP</key> \n\
    <integer>6</integer> \n\
    <key>TurboDisable</key> \n\
    <true/> \n\
    <key>Type</key> \n\
    <string>0x5</string> \n\
    <key>UseARTFrequency</key> \n\
    <true/> \n\
  </dict> \n\
  <key>Devices</key> \n\
  <dict> \n\
    <key>AddProperties</key> \n\
    <array> \n\
      <dict> \n\
        <key>Device</key> \n\
        <string>SATA</string> \n\
        <key>Disabled</key> \n\
        <false/> \n\
        <key>Key</key> \n\
        <string>10</string> \n\
        <key>Value</key> \n\
        <integer>11</integer> \n\
      </dict> \n\
      <dict> \n\
        <key>Device</key> \n\
        <string>LPC</string> \n\
        <key>Disabled</key> \n\
        <true/> \n\
        <key>Key</key> \n\
        <string>12</string> \n\
        <key>Value</key> \n\
        <integer>13</integer> \n\
      </dict> \n\
      <dict> \n\
        <key>Device</key> \n\
        <string>SmBUS</string> \n\
        <key>Disabled</key> \n\
        <false/> \n\
        <key>Key</key> \n\
        <string>kk</string> \n\
        <key>Value</key> \n\
        <string>ll</string> \n\
      </dict> \n\
      <dict> \n\
        <key>Device</key> \n\
        <string>Firewire</string> \n\
        <key>Disabled</key> \n\
        <false/> \n\
        <key>Key</key> \n\
        <string>14</string> \n\
        <key>Value</key> \n\
        <data> \n\
        FQ== \n\
        </data> \n\
      </dict> \n\
    </array> \n\
    <key>AirportBridgeDeviceName</key> \n\
    <string>airportbridge</string> \n\
    <key>Arbitrary</key> \n\
    <array> \n\
      <dict> \n\
        <key>Comment</key> \n\
        <string>C1</string> \n\
        <key>CustomProperties</key> \n\
        <array> \n\
          <dict> \n\
            <key>Disabled</key> \n\
            <false/> \n\
            <key>Key</key> \n\
            <string>ll</string> \n\
            <key>Value</key> \n\
            <string>mm</string> \n\
          </dict> \n\
          <dict> \n\
            <key>Disabled</key> \n\
            <true/> \n\
            <key>Key</key> \n\
            <string>nn</string> \n\
            <key>Value</key> \n\
            <integer>1</integer> \n\
          </dict> \n\
          <dict> \n\
            <key>Disabled</key> \n\
            <false/> \n\
            <key>Key</key> \n\
            <string>oo</string> \n\
            <key>Value</key> \n\
            <data> \n\
            Ag== \n\
            </data> \n\
          </dict> \n\
        </array> \n\
        <key>PciAddr</key> \n\
        <string>00:00.01</string> \n\
      </dict> \n\
    </array> \n\
    <key>Audio</key> \n\
    <dict> \n\
      <key>AFGLowPowerState</key> \n\
      <true/> \n\
      <key>Inject</key> \n\
      <string>Detect</string> \n\
      <key>ResetHDA</key> \n\
      <true/> \n\
    </dict> \n\
    <key>DisableFunctions</key> \n\
    <true/> \n\
    <key>FakeID</key> \n\
    <dict> \n\
      <key>ATI</key> \n\
      <string>0x22221002</string> \n\
      <key>IMEI</key> \n\
      <string>0x22221002</string> \n\
      <key>IntelGFX</key> \n\
      <string>0x22221002</string> \n\
      <key>LAN</key> \n\
      <string>0x22221002</string> \n\
      <key>NVidia</key> \n\
      <string>0x22221002</string> \n\
      <key>SATA</key> \n\
      <string>0x22221002</string> \n\
      <key>WIFI</key> \n\
      <string>0x22221002</string> \n\
      <key>XHCI</key> \n\
      <string>0x22221002</string> \n\
    </dict> \n\
    <key>ForceHPET</key> \n\
    <true/> \n\
    <key>Inject</key> \n\
    <true/> \n\
    <key>IntelMaxValue</key> \n\
    <true/> \n\
    <key>LpcTune</key> \n\
    <true/> \n\
    <key>NoDefaultProperties</key> \n\
    <true/> \n\
    <key>Properties</key> \n\
    <string>jj \n\
kk</string> \n\
    <key>SetIntelBacklight</key> \n\
    <true/> \n\
    <key>SetIntelMaxBacklight</key> \n\
    <true/> \n\
    <key>USB</key> \n\
    <dict> \n\
      <key>AddClockID</key> \n\
      <true/> \n\
      <key>FixOwnership</key> \n\
      <true/> \n\
      <key>HighCurrent</key> \n\
      <true/> \n\
      <key>Inject</key> \n\
      <true/> \n\
    </dict> \n\
    <key>UseIntelHDMI</key> \n\
    <true/> \n\
  </dict> \n\
  <key>DisableDrivers</key> \n\
  <array> \n\
    <string>OsxAptioFixDrv</string> \n\
    <string>Ps2KeyboardDxe</string> \n\
    <string>Ps2MouseDxe</string> \n\
  </array> \n\
  <key>GUI</key> \n\
  <dict> \n\
    <key>ConsoleMode</key> \n\
    <string>Max</string> \n\
    <key>Custom</key> \n\
    <dict> \n\
      <key>Entries</key> \n\
      <array> \n\
        <dict> \n\
          <key>AddArguments</key> \n\
          <string>addarg</string> \n\
          <key>Arguments</key> \n\
          <string>arg</string> \n\
          <key>BootBgColor</key> \n\
          <string>bootbgcolor</string> \n\
          <key>Disabled</key> \n\
          <false/> \n\
          <key>DriveImage</key> \n\
          <string>driveimage</string> \n\
          <key>FullTitle</key> \n\
          <string>title</string> \n\
          <key>Hidden</key> \n\
          <false/> \n\
          <key>Hotkey</key> \n\
          <string>H</string> \n\
          <key>Ignore</key> \n\
          <true/> \n\
          <key>ImageData</key> \n\
          <string>89 50 4E 47  0D 0A 1A 0A  00 00 00 0D  49 48 44 52 \n\
          00 00 01 00  00 00 01 00  01 03 00 00  00 66 BC 3A \n\
          25 00 00 00  03 50 4C 54  45 B5 D0 D0  63 04 16 EA \n\
          00 00 00 1F  49 44 41 54  68 81 ED C1  01 0D 00 00 \n\
          00 C2 A0 F7  4F 6D 0E 37  A0 00 00 00  00 00 00 00 \n\
          00 BE 0D 21  00 00 01 9A  60 E1 D5 00  00 00 00 49 \n\
          45 4E 44 AE  42 60 82  </string> \n\
          <key>xCustomLogo</key> \n\
          <string>foo</string> \n\
          <key>Path</key> \n\
          <string>CustomEntry1</string> \n\
          <key>Settings</key> \n\
          <string>settings</string> \n\
          <key>SubEntries</key> \n\
          <array> \n\
            <dict> \n\
              <key>AddArguments</key> \n\
              <string>arg2</string> \n\
              <key>FullTitle</key> \n\
              <string>title1</string> \n\
            </dict> \n\
            <dict> \n\
              <key>AddArguments</key> \n\
              <string>arg3</string> \n\
              <key>Title</key> \n\
              <string>title2</string> \n\
            </dict> \n\
            <dict> \n\
              <key>AddArguments</key> \n\
              <string>arg4</string> \n\
              <key>FullTitle</key> \n\
              <string>title3</string> \n\
            </dict> \n\
            <dict> \n\
              <key>AddArguments</key> \n\
              <string>arg5</string> \n\
              <key>Title</key> \n\
              <string>title4</string> \n\
            </dict> \n\
          </array> \n\
          <key>Type</key> \n\
          <string>Oldest</string> \n\
          <key>Volume</key> \n\
          <string>v1</string> \n\
          <key>VolumeType</key> \n\
          <string>Internal</string> \n\
        </dict> \n\
      </array> \n\
      <key>Legacy</key> \n\
      <array> \n\
        <dict> \n\
          <key>Disabled</key> \n\
          <true/> \n\
          <key>FullTitle</key> \n\
          <string>title</string> \n\
          <key>Hidden</key> \n\
          <true/> \n\
          <key>Hotkey</key> \n\
          <string></string> \n\
          <key>Ignore</key> \n\
          <true/> \n\
          <key>Type</key> \n\
          <string>Windows</string> \n\
          <key>Volume</key> \n\
          <string>v2</string> \n\
        </dict> \n\
      </array> \n\
      <key>Tool</key> \n\
      <array> \n\
        <dict> \n\
          <key>Arguments</key> \n\
          <string>b</string> \n\
          <key>Disabled</key> \n\
          <true/> \n\
          <key>Hidden</key> \n\
          <true/> \n\
          <key>Hotkey</key> \n\
          <string>b</string> \n\
          <key>Ignore</key> \n\
          <true/> \n\
          <key>Path</key> \n\
          <string>path</string> \n\
          <key>Title</key> \n\
          <string>title</string> \n\
          <key>Volume</key> \n\
          <string>tool1</string> \n\
        </dict> \n\
      </array> \n\
    </dict> \n\
    <key>CustomIcons</key> \n\
    <true/> \n\
    <key>Hide</key> \n\
    <array> \n\
      <string>sdfsdfdf</string> \n\
      <string>sdfsfdf</string> \n\
    </array> \n\
    <key>Language</key> \n\
    <string>es:0</string> \n\
    <key>Mouse</key> \n\
    <dict> \n\
      <key>DoubleClick</key> \n\
      <integer>501</integer> \n\
      <key>Enabled</key> \n\
      <true/> \n\
      <key>Mirror</key> \n\
      <true/> \n\
      <key>Speed</key> \n\
      <integer>5</integer> \n\
    </dict> \n\
    <key>Scan</key> \n\
    <dict> \n\
      <key>Entries</key> \n\
      <true/> \n\
      <key>Kernel</key> \n\
      <string>First</string> \n\
      <key>Legacy</key> \n\
      <string>First</string> \n\
      <key>Linux</key> \n\
      <true/> \n\
      <key>Tool</key> \n\
      <true/> \n\
    </dict> \n\
    <key>ScreenResolution</key> \n\
    <string>1366x768</string> \n\
    <key>ShowOptimus</key> \n\
    <true/> \n\
    <key>TextOnly</key> \n\
    <true/> \n\
    <key>Theme</key> \n\
    <string>th</string> \n\
  </dict> \n\
  <key>Graphics</key> \n\
  <dict> \n\
    <key>ATI</key> \n\
    <array> \n\
      <dict> \n\
        <key>IOPCIPrimaryMatch</key> \n\
        <string>0x1002888</string> \n\
        <key>IOPCISubDevId</key> \n\
        <string>0x106B</string> \n\
        <key>LoadVBios</key> \n\
        <true/> \n\
        <key>Model</key> \n\
        <string>cc</string> \n\
        <key>VRAM</key> \n\
        <integer>2000</integer> \n\
        <key>VideoPorts</key> \n\
        <integer>3</integer> \n\
      </dict> \n\
    </array> \n\
    <key>BootDisplay</key> \n\
    <integer>12</integer> \n\
    <key>DualLink</key> \n\
    <integer>1</integer> \n\
    <key>EDID</key> \n\
    <dict> \n\
      <key>Custom</key> \n\
      <data> \n\
      AQID \n\
      </data> \n\
      <key>Inject</key> \n\
      <true/> \n\
      <key>ProductID</key> \n\
      <string>0x9777</string> \n\
      <key>VendorID</key> \n\
      <string>0x1007</string> \n\
    </dict> \n\
    <key>FBName</key> \n\
    <string>Exmoor</string> \n\
    <key>Inject</key> \n\
    <dict> \n\
      <key>ATI</key> \n\
      <true/> \n\
      <key>Intel</key> \n\
      <true/> \n\
      <key>NVidia</key> \n\
      <true/> \n\
    </dict> \n\
    <key>LoadVBios</key> \n\
    <true/> \n\
    <key>NVCAP</key> \n\
    <string>0304</string> \n\
    <key>NVIDIA</key> \n\
    <array> \n\
      <dict> \n\
        <key>IOPCIPrimaryMatch</key> \n\
        <string>0x10DE999</string> \n\
        <key>IOPCISubDevId</key> \n\
        <string>0x106B</string> \n\
        <key>LoadVBios</key> \n\
        <false/> \n\
        <key>Model</key> \n\
        <string>aa</string> \n\
        <key>VRAM</key> \n\
        <integer>1000</integer> \n\
        <key>VideoPorts</key> \n\
        <integer>1</integer> \n\
      </dict> \n\
      <dict> \n\
        <key>IOPCIPrimaryMatch</key> \n\
        <string>0x10DE999</string> \n\
        <key>IOPCISubDevId</key> \n\
        <string>0x106B</string> \n\
        <key>LoadVBios</key> \n\
        <true/> \n\
        <key>Model</key> \n\
        <string>bb</string> \n\
        <key>VRAM</key> \n\
        <integer>1000</integer> \n\
        <key>VideoPorts</key> \n\
        <integer>2</integer> \n\
      </dict> \n\
    </array> \n\
    <key>NvidiaGeneric</key> \n\
    <true/> \n\
    <key>NvidiaNoEFI</key> \n\
    <true/> \n\
    <key>NvidiaSingle</key> \n\
    <true/> \n\
    <key>PatchVBios</key> \n\
    <true/> \n\
    <key>PatchVBiosBytes</key> \n\
    <array> \n\
      <dict> \n\
        <key>Find</key> \n\
        <data> \n\
        AwQF \n\
        </data> \n\
        <key>Replace</key> \n\
        <data> \n\
        BgcI \n\
        </data> \n\
      </dict> \n\
    </array> \n\
    <key>VRAM</key> \n\
    <integer>1500</integer> \n\
    <key>VideoPorts</key> \n\
    <integer>2</integer> \n\
    <key>display-cfg</key> \n\
    <string>04</string> \n\
    <key>ig-platform-id</key> \n\
    <string>0x59230000</string> \n\
  </dict> \n\
  <key>KernelAndKextPatches</key> \n\
  <dict> \n\
    <key>ATIConnectorsController</key> \n\
    <string>ATICtl</string> \n\
    <key>ATIConnectorsData</key> \n\
    <string>111213</string> \n\
    <key>ATIConnectorsPatch</key> \n\
    <string>141516</string> \n\
    <key>AppleIntelCPUPM</key> \n\
    <true/> \n\
    <key>AppleRTC</key> \n\
    <true/> \n\
    <key>BootPatches</key> \n\
    <array> \n\
      <dict> \n\
        <key>Comment</key> \n\
        <string>c3</string> \n\
        <key>Disabled</key> \n\
        <true/> \n\
        <key>Find</key> \n\
        <data> \n\
        MTI= \n\
        </data> \n\
        <key>MatchBuild</key> \n\
        <string>10.12.6</string> \n\
        <key>MatchOS</key> \n\
        <string>10.12</string> \n\
        <key>Replace</key> \n\
        <data> \n\
        MzQ= \n\
        </data> \n\
      </dict> \n\
    </array> \n\
    <key>Debug</key> \n\
    <true/> \n\
    <key>DellSMBIOSPatch</key> \n\
    <true/> \n\
    <key>FakeCPUID</key> \n\
    <string>0x0306D0</string> \n\
    <key>ForceKextsToLoad</key> \n\
    <array> \n\
      <string>ForceKext</string> \n\
    </array> \n\
    <key>KernelCpu</key> \n\
    <true/> \n\
    <key>KernelLapic</key> \n\
    <true/> \n\
    <key>KernelPm</key> \n\
    <true/> \n\
    <key>KernelToPatch</key> \n\
    <array> \n\
      <dict> \n\
        <key>Comment</key> \n\
        <string>c2</string> \n\
        <key>Disabled</key> \n\
        <true/> \n\
        <key>Find</key> \n\
        <data> \n\
        ISI= \n\
        </data> \n\
        <key>MatchBuild</key> \n\
        <string>10.13.6</string> \n\
        <key>MatchOS</key> \n\
        <string>10.13</string> \n\
        <key>Replace</key> \n\
        <data> \n\
        IyQ= \n\
        </data> \n\
      </dict> \n\
    </array> \n\
    <key>KernelXCPM</key> \n\
    <true/> \n\
    <key>KextsToPatch</key> \n\
    <array> \n\
      <dict> \n\
        <key>Comment</key> \n\
        <string>c1</string> \n\
        <key>Disabled</key> \n\
        <true/> \n\
        <key>Find</key> \n\
        <data> \n\
        AQ== \n\
        </data> \n\
        <key>InfoPlistPatch</key> \n\
        <true/> \n\
        <key>MatchBuild</key> \n\
        <string>10.14.6</string> \n\
        <key>MatchOS</key> \n\
        <string>10.14</string> \n\
        <key>Name</key> \n\
        <string>k1</string> \n\
        <key>Replace</key> \n\
        <data> \n\
        Ag== \n\
        </data> \n\
      </dict> \n\
      <dict> \n\
        <key>Comment</key> \n\
        <string>IONVMeFamily IONameMatch</string> \n\
        <key>Disabled</key> \n\
        <false/> \n\
        <key>Find</key> \n\
        <data> \n\
        PHN0cmluZz5wY2kxNDRkLGE4MDQ8L3N0cmluZz4= \n\
        </data> \n\
        <key>InfoPlistPatch</key> \n\
        <true/> \n\
        <key>Name</key> \n\
        <string>IONVMeFamily</string> \n\
        <key>Replace</key> \n\
        <data> \n\
        PHN0cmluZz5wY2kxNDRkLGE4MDI8L3N0cmluZz4= \n\
        </data> \n\
      </dict> \n\
    </array> \n\
  </dict> \n\
  <key>RtVariables</key> \n\
  <dict> \n\
    <key>BooterConfig</key> \n\
    <string>0x1</string> \n\
    <key>CsrActiveConfig</key> \n\
    <string>0x2</string> \n\
    <key>MLB</key> \n\
    <string>12345678901234567</string> \n\
    <key>ROM</key> \n\
    <data> \n\
    MBRwYnHo \n\
    </data> \n\
  </dict> \n\
  <key>SMBIOS</key> \n\
  <dict> \n\
    <key>BiosReleaseDate</key> \n\
    <string>08/08/17</string> \n\
    <key>BiosVendor</key> \n\
    <string>Apple Inc.</string> \n\
    <key>BiosVersion</key> \n\
    <string>MBP81.88Z.004D.B00.1708080655</string> \n\
    <key>Board-ID</key> \n\
    <string>Mac-94245B3640C91C81</string> \n\
    <key>BoardManufacturer</key> \n\
    <string>Apple Inc.</string> \n\
    <key>BoardSerialNumber</key> \n\
    <string>W89135306OPDM6CAD</string> \n\
    <key>BoardType</key> \n\
    <integer>10</integer> \n\
    <key>BoardVersion</key> \n\
    <string>1.0</string> \n\
    <key>ChassisAssetTag</key> \n\
    <string>MacBook-Aluminum</string> \n\
    <key>ChassisManufacturer</key> \n\
    <string>Apple Inc.</string> \n\
    <key>ChassisType</key> \n\
    <string>0x0A</string> \n\
    <key>Family</key> \n\
    <string>MacBook Pro</string> \n\
    <key>FirmwareFeatures</key> \n\
    <string>0xC00DE137</string> \n\
    <key>FirmwareFeaturesMask</key> \n\
    <string>0xFF1FFF3F</string> \n\
    <key>LocationInChassis</key> \n\
    <string>Part Component</string> \n\
    <key>Manufacturer</key> \n\
    <string>Apple Inc.</string> \n\
    <key>Memory</key> \n\
    <dict> \n\
      <key>Channels</key> \n\
      <integer>2</integer> \n\
      <key>Modules</key> \n\
      <array> \n\
        <dict> \n\
          <key>Frequency</key> \n\
          <integer>333</integer> \n\
          <key>Part</key> \n\
          <string>Part1</string> \n\
          <key>Serial</key> \n\
          <string>Ser1</string> \n\
          <key>Size</key> \n\
          <integer>2048</integer> \n\
          <key>Slot</key> \n\
          <integer>1</integer> \n\
          <key>Type</key> \n\
          <string>DDR</string> \n\
          <key>Vendor</key> \n\
          <string>v1</string> \n\
        </dict> \n\
        <dict> \n\
          <key>Frequency</key> \n\
          <integer>366</integer> \n\
          <key>Part</key> \n\
          <string>Part2</string> \n\
          <key>Serial</key> \n\
          <string>Ser2</string> \n\
          <key>Size</key> \n\
          <integer>4096</integer> \n\
          <key>Slot</key> \n\
          <integer>2</integer> \n\
          <key>Type</key> \n\
          <string>DDR2</string> \n\
          <key>Vendor</key> \n\
          <string>v2</string> \n\
        </dict> \n\
      </array> \n\
      <key>SlotCount</key> \n\
      <integer>4</integer> \n\
    </dict> \n\
    <key>Mobile</key> \n\
    <true/> \n\
    <key>PlatformFeature</key> \n\
    <string>0xFFFF</string> \n\
    <key>ProductName</key> \n\
    <string>MacBookPro8,1</string> \n\
    <key>SerialNumber</key> \n\
    <string>W89G91VFDH2G</string> \n\
    <key>Slots</key> \n\
    <array> \n\
      <dict> \n\
        <key>Device</key> \n\
        <string>NVidia</string> \n\
        <key>ID</key> \n\
        <integer>1</integer> \n\
        <key>Name</key> \n\
        <string>APPL,sdfsdf</string> \n\
        <key>Type</key> \n\
        <integer>1</integer> \n\
      </dict> \n\
    </array> \n\
    <key>SmUUID</key> \n\
    <string>F1AB23C0-C35A-473E-BDB7-455C3A6271E8</string> \n\
    <key>Version</key> \n\
    <string>1.0</string> \n\
  </dict> \n\
  <key>SystemParameters</key> \n\
  <dict> \n\
    <key>BacklightLevel</key> \n\
    <string>2</string> \n\
    <key>CustomUUID</key> \n\
    <string>2926A57C-FF0E-4A64-980F-23483BD41969</string> \n\
    <key>ExposeSysVariables</key> \n\
    <true/> \n\
    <key>InjectKexts</key> \n\
    <string>Yes</string> \n\
    <key>InjectSystemID</key> \n\
    <true/> \n\
    <key>NoCaches</key> \n\
    <true/> \n\
    <key>NvidiaWeb</key> \n\
    <true/> \n\
  </dict> \n\
</dict> \n\
</plist>";

#endif //MSC_VER

#endif /* ConfigSample1_h */


/*

 <key>Test null data</key> \n\
 <data></data> \n\


*/
