#!/bin/bash

diskloader="boot0"
partitionloaderhfs="boot1h2"
partitionloaderfat="boot1f32alt"
install_log="${3}/Clover_Install_Log.txt"

start ()
{
# $1 volume

bootvolume="${@}"
echo "Volume is $bootvolume"
bootresources="${0%/*}"
echo "$bootresources"

if [ -z "${bootvolume}" ]; then
	echo
	echo "Cannot find the volume. Exiting."
	echo
	exit
fi

bootdev=$( df "${bootvolume}" | sed -n '2p' | awk '{print $1}' )
bootrdev=${bootdev/disk/rdisk}

if [ "${bootdev}" = "${bootdev#*disk*s}" ]; then
	echo
	echo "ERROR Volume does not use slices."
	echo
	exit
fi

bootdisk=${bootdev%s*}
bootrdisk=${bootdisk/disk/rdisk}
bootslice=${bootdev#*disk*s}

echo "==============================================="
echo "Installer Variables:"
echo "********************"
echo "bootvolume: Volume is ${bootvolume}"
echo "bootdev: Volume device is ${bootdev}"
echo "bootrdev: Volume raw device is ${bootrdev}"
echo "bootslice: Volume slice is ${bootslice}"
echo "bootdisk: Disk device is ${bootdisk}"
echo "bootrdisk: Disk raw device is ${bootrdisk}"
echo "diskloader: Disk loader is ${diskloader}"
echo "partitionloaderhfs: Partition loader is ${partitionloaderhfs}"
echo "partitionloaderfat: Partition loader is ${partitionloaderfat}"
echo "bootresources: Boot Resources is ${bootresources}"
echo "-----------------------------------------------"
echo ""
echo ""
}

start ${3}

if [ ! -e "/usr/local/bin/fdisk440" ]; then
	mkdir -p /usr/local/bin
	cp -f "${bootvolume}/usr/local/bin/fdisk440" /usr/local/bin/fdisk440
fi

echo "==============================================="
echo "Check the format of the selected partition"
echo "==============================================="

if [ "$( fstyp ${bootdev} | grep hfs )" ]; then
	echo "${bootdev} is currently formatted as HFS"
	efiformat="hfs"
fi
if [ "$( fstyp ${bootdev} | grep msdos )" ]; then
	echo "${bootdev} is currently formatted as msdos"
	efiformat="msdos"
fi
echo "-----------------------------------------------"

echo "======================================================" >> "$install_log"
echo "Installing BootSectors/BootLoader" >> "$install_log"
echo "" >> "$install_log"
partitionactive=$( /usr/local/bin/fdisk440 -d ${bootrdisk} | grep -n "*" | awk -F: '{print $1}')
echo "Current Active Partition: ${partitionactive}" >> "$install_log"
echo "" >> "$install_log"

### Stage 0 ###

echo "Stage 0 - Written ${diskloader} to ${bootdisk}" >> "$install_log"
echo "/usr/local/bin/fdisk440 -u -f ${bootvolume}/usr/standalone/i386/${diskloader} -y ${bootdisk}" >> "$install_log"
echo " " >> "$install_log"

"/usr/local/bin/fdisk440" -u -f "${bootvolume}/usr/standalone/i386/${diskloader}" -y ${bootdisk}

### Stage 1 ###

if [ ${efiformat} = "hfs" ]; then
	echo "Executing command: dd if=/usr/standalone/i386/${partitionloaderhfs} of=${bootrdev}"

	echo "Stage 1 - Written ${partitionloaderhfs} to ${bootrdev}" >> "$install_log"
	echo "File system is HFS." >> "$install_log"
	echo "dd if=${bootvolume}/usr/standalone/i386/${partitionloaderhfs} of=${bootrdev}" >> "$install_log"
	echo " " >> "$install_log"

	dd if="${bootvolume}/usr/standalone/i386/${partitionloaderhfs}" of=${bootrdev}

	echo "${efiformat}" > "${bootvolume}/formattype"
fi

if [ ${efiformat} = "msdos" ]; then

	rm -f /tmp/origbs
	rm -f /tmp/newbs

	echo "Prepare Stage 1 loader"
	# copy partition boot sector to origbs
	echo "Executing command: dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs"
	dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs

	# copy boot1f32 to newbs
	echo "Executing command: cp "${bootvolume}/usr/standalone/i386/${partitionloaderfat}" /tmp/newbs"
	cp "${bootvolume}/usr/standalone/i386/${partitionloaderfat}" /tmp/newbs

	# "merge" origbs into newbs
	echo "Executing command: dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc"
	dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc

	echo "Write Stage 1 loader"

	# write newbs to the partition boot sector
	echo "Executing command: dd if=/tmp/newbs of=${bootrdev}"
	dd if=/tmp/newbs of=${bootrdev}

	echo "Stage 1 - Written ${partitionloaderfat} to ${bootrdev}" >> "$install_log"
	echo "File system is Fat32." >> "$install_log"
	echo "dd if=${bootrdev} count=1 bs=512 of=/tmp/origbs" >> "$install_log"
	echo "cp ${bootvolume}/usr/standalone/i386/${partitionloaderfat} /tmp/newbs" >> "$install_log"
	echo "dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc" >> "$install_log"
	echo "dd if=/tmp/newbs of=${bootrdev}" >> "$install_log"
	echo " " >> "$install_log"

	echo "${efiformat}" > "${bootvolume}/formattype"
fi

echo "Setup Active Partition to be : ${bootslice}" >> "$install_log"
"/usr/local/bin/fdisk440" -e ${bootrdisk} <<-MAKEACTIVE
print
flag ${bootslice}
write
y
quit
MAKEACTIVE

partitionactive=$( /usr/local/bin/fdisk440 -d ${bootrdisk} | grep -n "*" | awk -F: '{print $1}')
echo "New Active Partition: ${partitionactive}" >> "$install_log"

echo "${diskloader}" > "${bootvolume}/boot0type"

exit
