#!/usr/bin/perl

$destino = $ARGV[1];
$destino =~ s/ /\\ /g;
$volume = $ARGV[2];
my %mapa;

open (MOUNT, "mount|");
while (<MOUNT>) {
	chomp;
	$line = $_;
	if ($line =~ /^([^ ]+) on ([^(]+) \([^)]*\)$/) {
		$mapa{$2}=$1;
	}
}
close (MOUNT);

if ($mapa{$volume}) {
	if ($mapa{$volume} =~ /^\/dev\/(disk\d)s(\d)$/) {
		$disk = $1;
		$partition = $2;
		$volume =~ s/ /\\ /g;
		system ("mkdir -p /usr/local/bin/");
		system ("cp -f ".$destino."/usr/local/bin/fdisk440  /usr/local/bin/fdisk440");
		system ("/usr/local/bin/fdisk440 -f ".$destino."/usr/standalone/i386/boot0hfs -u -y /dev/r".$disk);
		system ("dd if=".$destino."/usr/standalone/i386/boot1h2 of=/dev/r".$disk."s".$partition);
		system ("echo boot0hfs > ".$destino."/installtype");
	}
}