#!/bin/bash

echo "====================================================="
echo " "
echo "Don't install any of boot1f32alt, boot1h and boot1h2,"
echo "used for 4kb harddisk with manual install."
echo " "
echo "====================================================="

