#!/usr/bin/perl

$destino = $ARGV[1];
$destino =~ s/ /\\ /g;
$volume = $ARGV[2];
my %mapa;

open (MOUNT, "mount|");
while (<MOUNT>) {
	chomp;
	$line = $_;
	if ($line =~ /^([^ ]+) on ([^(]+) \([^)]*\)$/) {
		$mapa{$2}=$1;
	}
}
close (MOUNT);

if ($mapa{$volume}) {
	if ($mapa{$volume} =~ /^\/dev\/(disk\d)s(\d)$/) {
		$disk = $1;
		$partition = $2;
		$volume =~ s/ /\\ /g;
		system ($destino."/usr/sbin/fdisk440 -f ".$destino."/usr/standalone/i386/boot0 -u -y /dev/r".$disk);
		system ("dd if=".$destino."/usr/standalone/i386/boot1h2 of=/dev/r".$disk."s".$partition);
		
		system ("cp ".$volume."/boot ".$volume."/bootold");
		system ("cp ".$destino."/usr/standalone/i386/x64/boot ".$volume."/boot");
		system ("cp ".$destino."/usr/standalone/i386/x64/boot ".$volume."/boot1");
		system ("chflags hidden ".$volume."/boot");
		system ("chflags hidden ".$volume."/boot1");
		
		system ("cp -f ".$destino."/EFI/config-x64.plist ".$volume."/EFI/config-org.plist");
		system ("rm -f ".$destino."/EFI/drivers/*32.efi");
		open (PIPE, "|fdisk -e /dev/".$disk."|");
		print PIPE "f ".$partition."\n";
		print PIPE "write\n";
		print PIPE "y\n";
		print PIPE "exit\n";
	}
}