#!/bin/bash

echo "==============================================="
echo "BootLoaderChooser Post-Install Script"
echo "==============================================="

echo "postinstall: Path to installer....... $1"
echo "postinstall: Path to destination..... $2"
echo "postinstall: Path to dest volume..... $3"
echo "postinstall: Root of system folder... $4"

######################################################
# If target volume root of current system then replace
# / with volume name.
DEST_VOL="${3}"
EFI_ROOT_DIR=$(cd "${DEST_VOL}"/Private/tmp/EFIROOTDIR; pwd -P)
CLOVER_INSTALLER_PLIST_NEW="${DEST_VOL}@CLOVER_INSTALLER_PLIST_NEW@"

install_log="${DEST_VOL}/Private/tmp/Clover_Install_Log.txt"
installer_choice="@INSTALLER_CHOICE@"

boottype='@CLOVER_EFI_ARCH@'
cloverEFIFile='@CLOVER_BOOT_FILE@'


# Mark that the option was selected
/usr/libexec/PlistBuddy -c "Add $installer_choice bool true" "$CLOVER_INSTALLER_PLIST_NEW" >/dev/null
