#!/bin/bash

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"
install_log="${osxvolume}/Clover_Install_Log.txt"
installer_plist="${osxvolume}/EFI/CloverInstaller.plist"
installer_choice="@INSTALLER_CHOICE@"

# Mark that the option was selected
/usr/libexec/plistbuddy -c "Add $installer_choice bool true" "$installer_plist" >/dev/null
