#!/bin/bash

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"

echo "====================================================="
echo " "
echo "Don't install any of boot1f32alt, boot1h and boot1h2,"
echo "used for 4kb harddisk with manual install."
echo " "
echo "====================================================="

echo Stage 0 - Don"'"t write any of boot0, boot0hfs, boot0md to ${osxvolume} >> "${osxvolume}/Clover_Install_Log.txt"
echo "------------------------------------------------------" >> "${osxvolume}/Clover_Install_Log.txt"

echo Stage 1 - Don"'"t write any of boot1h2, boot1f32alt to ${osxvolume} >> "${osxvolume}/Clover_Install_Log.txt"
echo Don"'"t write boot0, boot1.. > "${osxvolume}/boot0type"
echo "------------------------------------------------------" >> "${osxvolume}/Clover_Install_Log.txt"
