# Auto-generated by /Users/vectorsigma/src/Clover/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/vectorsigma/src/Clover
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/vectorsigma/src/Clover/BaseTools
fi
if [ -e /Users/vectorsigma/src/Clover/BaseTools/Bin/Darwin-x86_64 ]
then
  if [ ${PATH//Users/vectorsigma/src/Clover/BaseTools/Bin/Darwin-x86_64/} == $PATH ]
  then
    export PATH=/Users/vectorsigma/src/Clover/BaseTools/Bin/Darwin-x86_64:$PATH
  fi
fi
