#!/usr/bin/perl

$destino = $ARGV[1];
$destino =~ s/ /\\ /g;
$volume = $ARGV[2];
my %mapa;

open (MOUNT, "mount|");
while (<MOUNT>) {
	chomp;
	$line = $_;
	if ($line =~ /^([^ ]+) on ([^(]+) \([^)]*\)$/) {
		$mapa{$2}=$1;
	}
}
close (MOUNT);

if ($mapa{$volume}) {
	if ($mapa{$volume} =~ /^\/dev\/(disk\d)s(\d)$/) {
		$disk = $1;
		$partition = $2;
		$volume =~ s/ /\\ /g;
		
		system ("cp ".$volume."/boot ".$volume."/bootold");
		system ("cp ".$destino."/usr/standalone/i386/ia32/boot ".$volume."/boot");
		system ("cp ".$destino."/usr/standalone/i386/ia32/boot ".$volume."/boot1");
		system ("chflags hidden ".$volume."/boot");
		system ("chflags hidden ".$volume."/boot1");
		
		system ("cp -f ".$destino."/EFI/config-x32.plist ".$volume."/EFI/config-org.plist");
		system ("rm -f ".$destino."/EFI/drivers/*64.efi");
		system ("rm -f ".$destino."/EFI/drivers/NTFS.efi");
	}
}