#!/bin/bash

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

osxvolume="${3}"
installtype=$( cat "${osxvolume}/boot0type" )

# Start to install boot, boot3, boot6.

cp "${osxvolume}/boot" "${osxvolume}/bootold"
cp "${osxvolume}/usr/standalone/i386/ia32/boot" "${osxvolume}/boot"
cp "${osxvolume}/usr/standalone/i386/ia32/boot" "${osxvolume}/boot3"
cp "${osxvolume}/usr/standalone/i386/x64/boot" "${osxvolume}/boot6"
chflags hidden "${osxvolume}/boot"
chflags hidden "${osxvolume}/boot3"
chflags hidden "${osxvolume}/boot6"
echo "x32" > "${osxvolume}/boottype"

echo "Stage 2 - Written boot to ${osxvolume}/" >> "${osxvolume}/Clover_Install_Log.txt"
echo "Boot Start type = x32" >> "${osxvolume}/Clover_Install_Log.txt"
echo "Install type = ${installtype}" >> "${osxvolume}/Clover_Install_Log.txt"

echo "cp ${osxvolume}/usr/standalone/i386/ia32/boot ${osxvolume}/boot" >> "${osxvolume}/Clover_Install_Log.txt"
echo "cp ${osxvolume}/usr/standalone/i386/ia32/boot ${osxvolume}/boot3" >> "${osxvolume}/Clover_Install_Log.txt"
echo "cp ${osxvolume}/usr/standalone/i386/x64/boot ${osxvolume}/boot6" >> "${osxvolume}/Clover_Install_Log.txt"
echo "======================================================" >> "${osxvolume}/Clover_Install_Log.txt"
