#!/bin/bash

echo "==============================================="
echo "Post-Install Optional RC Scripts"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

srcvolume="${3}"
destroot="${srcvolume}"
install_log="${srcvolume}/Clover_Install_Log.txt"
installer_plist="${srcvolume}/EFI/CloverInstaller.plist"
installer_choice="@INSTALLER_CHOICE@"

rc_script="@RC_SCRIPT@"

enabled_script="${rc_script%.disabled}"

# Mark that the option was selected
/usr/libexec/plistbuddy -c "Add $installer_choice bool true" "$installer_plist" >/dev/null

# Check if destination volume is a system volume:
if [[ ! -f "${destroot}/System/Library/CoreServices/boot.efi" ]]; then
    # Destination volume is not a system so install rc script into the system
    # folder
    destroot="$4"
fi

# Enable the RC script
echo "Activating ${destroot}/${enabled_script} rc script" >> "$install_log"
mv -f "$destroot/$rc_script" "$destroot/$enabled_script"  >> "$install_log"
