#ifdef __cplusplus
extern "C" {
#endif

///*
// * Generated by c++ compiler, but needs to be called manually from main.
// */
//void __cxx_global_var_init();
//
///*
// * Needs to be called manually before exiting Clover.efi module.
// */
//void __cxa_finalize(void *f);

#ifdef __cplusplus
}
#endif
