#!/bin/bash

echo "==============================================="
echo "AltBoot Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

DEST_VOL="$3"
EFI_ROOT_DIR="${DEST_VOL}/EFIROOTDIR"

for file in boot3 boot6 boot7; do
    if [[ -f "${EFI_ROOT_DIR}/$file" ]]; then
        chflags hidden "${EFI_ROOT_DIR}/$file"
    fi
done

exit 0
