#!/usr/bin/perl

$destino = $ARGV[1];
$destino =~ s/ /\\ /g;
$volume = $ARGV[2];
my %mapa;

open (MOUNT, "mount|");
while (<MOUNT>) {
	chomp;
	$line = $_;
	if ($line =~ /^([^ ]+) on ([^(]+) \([^)]*\)$/) {
		$mapa{$2}=$1;
	}
}
close (MOUNT);

if ($mapa{$volume}) {
	if ($mapa{$volume} =~ /^\/dev\/(disk\d)s(\d)$/) {
		$disk = $1;
		$partition = $2;
		$volume =~ s/ /\\ /g;
		system ("dd if=".$destino."/usr/standalone/i386/boot1h2 of=/dev/r".$disk."s".$partition);
		system ("echo boot1h2 > ".$destino."/EFI/boot1type");
	}
}