#!/bin/bash

echo "==============================================="
echo "Pre Pre-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

#############################################################################

DEST_VOL="${3}"
install_tmp="${DEST_VOL}/Private/tmp"
CLOVER_INSTALLER_PLIST_NEW="${DEST_VOL}@CLOVER_INSTALLER_PLIST_NEW@"
CLOVER_INSTALLER_PLIST_NEW_DIR=$(dirname "$CLOVER_INSTALLER_PLIST_NEW")

[[ ! -d "$CLOVER_INSTALLER_PLIST_NEW_DIR" ]] && mkdir -p "$CLOVER_INSTALLER_PLIST_NEW_DIR"
rm -f "$CLOVER_INSTALLER_PLIST_NEW"
mkdir -p "$install_tmp"
exit 0
