#!/bin/bash

echo "==============================================="
echo "EFIFolder Pre-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

# Check target exists
if [ ! -e "$3" ]; then
    echo "$3 volume does not exist!"
    exit 1
fi

# If target volume root of current system then replace
# / with volume name.
if [ "$3" == "/" ]; then
    dest_vol="/Volumes/"$( ls -1F /Volumes | sed -n 's:@$::p' )
else
    dest_vol="$3"
fi
install_log="${dest_vol}/Clover_Install_Log.txt"

# ---------------------------------------------
# Preparing Backing up of Clover files
# ---------------------------------------------
backupRootDir="$dest_vol/EFI-Backups"
backupDir="${backupRootDir}/"$( date -j "+%F-%Hh%M" )

# Create the backup dirextory
mkdir -p "$backupDir"

# ---------------------------------------------
# Backing up Clover files
# ---------------------------------------------

echo "" > "$install_log"
echo "Clover EFI installer log - $( date )" >> "$install_log"
echo "Installer version: %CLOVERVERSION% r%CLOVERREVISION% EFI bootloader" >> "$install_log"
echo "======================================================" >> "$install_log"
diskutil list >> "$install_log"

echo "======================================================" >> "$install_log"
echo "Backing up EFI files" >> "$install_log"
echo "" >> "$install_log"

# Backup stage2
if [ -f "$dest_vol/boot" ];then
    echo "Backing up stage2 file $dest_vol/boot  to ${backupDir}/boot" >> "$install_log"
    cp -p "$dest_vol/boot" "${backupDir}/boot"
fi
if [ -f "$dest_vol/boot1" ];then
    echo "Backing up stage2 file $dest_vol/boot1 to ${backupDir}/boot1" >> "$install_log"
    cp -p "$dest_vol/boot1" "${backupDir}/boot1"
fi
if [ -f "$dest_vol/boot3" ];then
    echo "Backing up stage2 file $dest_vol/boot3 to ${backupDir}/boot3" >> "$install_log"
    cp -p "$dest_vol/boot3" "${backupDir}/boot3"
fi
if [ -f "$dest_vol/boot6" ];then
    echo "Backing up stage2 file $dest_vol/boot6 to ${backupDir}/boot6" >> "$install_log"
    cp -p "$dest_vol/boot6" "${backupDir}/boot6"
fi

# Backup /EFI directory
if [ -d "$dest_vol/EFI" ];then
    echo "Backing up $dest_vol/EFI folder to ${backupDir}/EFI"   >> "$install_log"
    cp -pR "$dest_vol/EFI" "${backupDir}/EFI"
fi

chflags -R nohidden "$backupDir" # Remove the invisible flag of files in the backups

find "$backupRootDir" -type d -depth 1 -empty -exec rmdir {} \; # Remove empty directories

# Remove efi files of old revision (currently all in EFI/drivers* and EFI/BOOT/themes).
pkgs=$(/usr/sbin/pkgutil --volume "$dest_vol" --pkgs | /usr/bin/grep -iE '@CLOVER_PACKAGE_IDENTITY@.')
for pkg in $pkgs; do
    # Get where the files where installed from volume destination
    location=$(/usr/sbin/pkgutil --volume "$dest_vol" --pkg-info $pkg 2>/dev/null |  sed -n 's/^location: *//p')
    pkgutil --volume "$dest_vol" --files $pkg 2>/dev/null | \
        xargs -I @@ echo "$dest_vol/$location/@@"         | \
        /usr/bin/grep -iE 'EFI/(BOOT/themes|drivers\w+)/' | \
        xargs rm -rf
done

# Remove old Clover Installer plist if exists
rm -f "${dest_vol}/EFI/CloverInstaller.plist"
