
# auto-generated by configure
PREFIX = /usr/local
LIBDIR = /usr/local/lib
INCLUDEDIR = /usr/local/include
PKGCONFIGDIR = /usr/local/lib/pkgconfig
VERSION = 2.12.6
CC = gcc
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -mmacosx-version-min=10.7
LDFLAGS =  -mmacosx-version-min=10.7 -lm
SOLIBSUFFIX = dylib

