#!/usr/bin/perl

$destino = $ARGV[1];
$destino =~ s/ /\\ /g;
$volume = $ARGV[2];
my %mapa;

open (MOUNT, "mount|");
while (<MOUNT>) {
	chomp;
	$line = $_;
	if ($line =~ /^([^ ]+) on ([^(]+) \([^)]*\)$/) {
		$mapa{$2}=$1;
	}
}
close (MOUNT);

if ($mapa{$volume}) {
	if ($mapa{$volume} =~ /^\/dev\/(disk\d)s(\d)$/) {
		$disk = $1;
		$partition = $2;
		$volume =~ s/ /\\ /g;
		
		system ("cp ".$volume."/boot ".$volume."/bootold");
		system ("cp ".$destino."/usr/standalone/i386/x64/boot ".$volume."/boot");
		system ("cp ".$destino."/usr/standalone/i386/ia32/boot ".$volume."/boot3");
		system ("cp ".$destino."/usr/standalone/i386/x64/boot ".$volume."/boot6");
		system ("chflags hidden ".$volume."/boot");
		system ("chflags hidden ".$volume."/boot3");
		system ("chflags hidden ".$volume."/boot6");
		system ("echo x64 > ".$destino."/EFI/boottype");
	}
}